//! IronRDP clipboard backend integration.
//!
//! This module bridges IronRDP CLIPRDR callbacks to the server clipboard
//! orchestrator. The IronRDP backend trait is synchronous, so callbacks enqueue
//! small owned events that an async task forwards into the orchestrator.

use std::{
    collections::VecDeque,
    sync::{Arc, RwLock},
};

pub use ironrdp_cliprdr::pdu::ClipboardGeneralCapabilityFlags;
use ironrdp_cliprdr::{
    backend::{CliprdrBackend, CliprdrBackendFactory},
    pdu::{
        ClipboardFormat as RdpClipboardFormat, ClipboardFormatId, FileContentsFlags,
        FileContentsRequest, FileContentsResponse, FormatDataRequest, FormatDataResponse,
        LockDataId,
    },
};
use ironrdp_core::AsAny;
use ironrdp_server::ServerEventSender;
use tokio::sync::{Mutex, mpsc};
use tracing::{debug, info};

use crate::rdp::channels::clipboard::{core::ClipboardFormat, manager::ClipboardOrchestrator};

/// Events generated by the IronRDP clipboard backend for async processing.
#[derive(Debug, Clone)]
pub enum ClipboardEvent {
    /// Backend is ready.
    Ready,
    /// Client requested a format list.
    RequestFormatList,
    /// Negotiated capabilities received.
    NegotiatedCapabilities(ClipboardGeneralCapabilityFlags),
    /// Remote clipboard content changed.
    RemoteCopy {
        /// Available formats from the remote side.
        formats: Vec<RdpClipboardFormat>,
    },
    /// Remote requests format data.
    FormatDataRequest {
        /// Requested format ID.
        format_id: ClipboardFormatId,
    },
    /// Remote sent format data response.
    FormatDataResponse {
        /// Returned data.
        data: Vec<u8>,
        /// Whether this is an error response.
        is_error: bool,
    },
    /// Remote requests file contents.
    FileContentsRequest {
        /// Stream ID for correlation.
        stream_id: u32,
        /// Signed file index from CLIPRDR `lindex`.
        index: i32,
        /// Byte offset.
        position: u64,
        /// Requested size.
        size: u32,
        /// Whether this is a size request.
        is_size_request: bool,
    },
    /// Remote sent file contents response.
    FileContentsResponse {
        /// Stream ID for correlation.
        stream_id: u32,
        /// File data.
        data: Vec<u8>,
        /// Whether this is an error response.
        is_error: bool,
    },
    /// Clipboard lock request.
    Lock {
        /// Data ID to lock.
        data_id: u32,
    },
    /// Clipboard unlock request.
    Unlock {
        /// Data ID to unlock.
        data_id: u32,
    },
}

impl ClipboardEvent {
    fn remote_copy(formats: &[RdpClipboardFormat]) -> Self {
        Self::RemoteCopy {
            formats: formats.to_vec(),
        }
    }

    fn format_data_request(request: &FormatDataRequest) -> Self {
        Self::FormatDataRequest {
            format_id: request.format,
        }
    }

    fn format_data_response(response: &FormatDataResponse<'_>) -> Self {
        Self::FormatDataResponse {
            data: response.data().to_vec(),
            is_error: response.is_error(),
        }
    }

    fn file_contents_request(request: &FileContentsRequest) -> Self {
        Self::FileContentsRequest {
            stream_id: request.stream_id,
            index: request.index,
            position: request.position,
            size: request.requested_size,
            is_size_request: request.flags.contains(FileContentsFlags::SIZE),
        }
    }

    fn file_contents_response(response: &FileContentsResponse<'_>) -> Self {
        Self::FileContentsResponse {
            stream_id: response.stream_id(),
            data: response.data().to_vec(),
            is_error: response.is_error(),
        }
    }

    fn lock(data_id: LockDataId) -> Self {
        Self::Lock { data_id: data_id.0 }
    }

    fn unlock(data_id: LockDataId) -> Self {
        Self::Unlock { data_id: data_id.0 }
    }
}

fn clipboard_formats_from_rdp(formats: &[RdpClipboardFormat]) -> Vec<ClipboardFormat> {
    formats
        .iter()
        .map(|format| ClipboardFormat {
            id: format.id().value(),
            name: format.name().map(|name| name.value().to_string()),
        })
        .collect()
}

/// Sender side of the clipboard event queue.
#[derive(Debug, Clone)]
pub struct ClipboardEventSender {
    queue: Arc<RwLock<VecDeque<ClipboardEvent>>>,
}

impl ClipboardEventSender {
    /// Create a new event sender.
    pub fn new() -> Self {
        Self {
            queue: Arc::new(RwLock::new(VecDeque::new())),
        }
    }

    /// Queue an event without blocking the protocol callback.
    pub fn send(&self, event: ClipboardEvent) {
        if let Ok(mut queue) = self.queue.try_write() {
            queue.push_back(event);
        } else {
            tracing::warn!("failed to acquire clipboard event queue lock");
        }
    }

    /// Create a receiver sharing this queue.
    pub fn subscribe(&self) -> ClipboardEventReceiver {
        ClipboardEventReceiver {
            queue: Arc::clone(&self.queue),
        }
    }
}

impl Default for ClipboardEventSender {
    fn default() -> Self {
        Self::new()
    }
}

/// Receiver side of the clipboard event queue.
#[derive(Debug, Clone)]
pub struct ClipboardEventReceiver {
    queue: Arc<RwLock<VecDeque<ClipboardEvent>>>,
}

impl ClipboardEventReceiver {
    /// Try to receive the next event without blocking.
    pub fn try_recv(&self) -> Option<ClipboardEvent> {
        self.queue.try_write().ok()?.pop_front()
    }

    /// Drain all pending events.
    pub fn drain(&self) -> Vec<ClipboardEvent> {
        self.queue
            .try_write()
            .ok()
            .map(|mut queue| queue.drain(..).collect())
            .unwrap_or_default()
    }

    /// Check whether there are pending events.
    pub fn has_pending(&self) -> bool {
        self.queue
            .try_read()
            .map(|queue| !queue.is_empty())
            .unwrap_or(false)
    }
}

/// IronRDP CLIPRDR backend used by `wrdp`.
#[derive(Debug)]
pub struct RdpCliprdrBackend {
    temp_dir: String,
    event_sender: ClipboardEventSender,
    capabilities: ClipboardGeneralCapabilityFlags,
    remote_formats: Vec<RdpClipboardFormat>,
    is_ready: bool,
}

impl RdpCliprdrBackend {
    /// Create a new backend.
    pub fn new(temp_dir: String, event_sender: ClipboardEventSender) -> Self {
        Self {
            temp_dir,
            event_sender,
            capabilities: ClipboardGeneralCapabilityFlags::empty(),
            remote_formats: Vec::new(),
            is_ready: false,
        }
    }

    /// Return the current remote format list.
    pub fn remote_formats(&self) -> &[RdpClipboardFormat] {
        &self.remote_formats
    }

    /// Check whether the backend has reached the ready state.
    pub fn is_ready(&self) -> bool {
        self.is_ready
    }

    /// Return negotiated capabilities.
    pub fn capabilities(&self) -> ClipboardGeneralCapabilityFlags {
        self.capabilities
    }

    /// Create a backend and event receiver pair.
    pub fn create_with_channel(temp_dir: String) -> (Self, ClipboardEventReceiver) {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();
        let backend = Self::new(temp_dir, sender);
        (backend, receiver)
    }
}

impl AsAny for RdpCliprdrBackend {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
        self
    }
}

impl CliprdrBackend for RdpCliprdrBackend {
    fn temporary_directory(&self) -> &str {
        &self.temp_dir
    }

    fn client_capabilities(&self) -> ClipboardGeneralCapabilityFlags {
        ClipboardGeneralCapabilityFlags::USE_LONG_FORMAT_NAMES
            | ClipboardGeneralCapabilityFlags::STREAM_FILECLIP_ENABLED
            | ClipboardGeneralCapabilityFlags::CAN_LOCK_CLIPDATA
            | ClipboardGeneralCapabilityFlags::FILECLIP_NO_FILE_PATHS
    }

    fn on_ready(&mut self) {
        debug!("clipboard backend ready");
        self.is_ready = true;
        self.event_sender.send(ClipboardEvent::Ready);
    }

    fn on_request_format_list(&mut self) {
        debug!("clipboard format list requested");
        self.event_sender.send(ClipboardEvent::RequestFormatList);
    }

    fn on_process_negotiated_capabilities(
        &mut self,
        capabilities: ClipboardGeneralCapabilityFlags,
    ) {
        debug!("negotiated clipboard capabilities: {:?}", capabilities);
        self.capabilities = capabilities;
        self.event_sender
            .send(ClipboardEvent::NegotiatedCapabilities(capabilities));
    }

    fn on_remote_copy(&mut self, available_formats: &[RdpClipboardFormat]) {
        debug!("remote clipboard copy: {} formats", available_formats.len());
        self.remote_formats = available_formats.to_vec();
        self.event_sender
            .send(ClipboardEvent::remote_copy(available_formats));
    }

    fn on_format_data_request(&mut self, request: FormatDataRequest) {
        debug!("clipboard format data request received");
        self.event_sender
            .send(ClipboardEvent::format_data_request(&request));
    }

    fn on_format_data_response(&mut self, response: FormatDataResponse<'_>) {
        debug!(
            "clipboard format data response: {} bytes, error={}",
            response.data().len(),
            response.is_error()
        );
        self.event_sender
            .send(ClipboardEvent::format_data_response(&response));
    }

    fn on_file_contents_request(&mut self, request: FileContentsRequest) {
        debug!(
            "clipboard file contents request: stream={}, index={}, pos={}, size={}",
            request.stream_id, request.index, request.position, request.requested_size
        );
        self.event_sender
            .send(ClipboardEvent::file_contents_request(&request));
    }

    fn on_file_contents_response(&mut self, response: FileContentsResponse<'_>) {
        debug!(
            "clipboard file contents response: stream={}, {} bytes",
            response.stream_id(),
            response.data().len()
        );
        self.event_sender
            .send(ClipboardEvent::file_contents_response(&response));
    }

    fn on_lock(&mut self, data_id: LockDataId) {
        debug!("clipboard lock: data_id={}", data_id.0);
        self.event_sender.send(ClipboardEvent::lock(data_id));
    }

    fn on_unlock(&mut self, data_id: LockDataId) {
        debug!("clipboard unlock: data_id={}", data_id.0);
        self.event_sender.send(ClipboardEvent::unlock(data_id));
    }
}

/// Factory for creating IronRDP clipboard backends with a shared event queue.
#[derive(Debug, Clone)]
pub struct RdpCliprdrFactory {
    temp_dir: String,
    event_sender: ClipboardEventSender,
}

impl RdpCliprdrFactory {
    /// Create a new factory.
    pub fn new(temp_dir: impl Into<String>) -> Self {
        Self {
            temp_dir: temp_dir.into(),
            event_sender: ClipboardEventSender::new(),
        }
    }

    /// Create a new factory with an existing event sender.
    pub fn with_event_sender(
        temp_dir: impl Into<String>,
        event_sender: ClipboardEventSender,
    ) -> Self {
        Self {
            temp_dir: temp_dir.into(),
            event_sender,
        }
    }

    /// Subscribe to events produced by all backends created by this factory.
    pub fn subscribe(&self) -> ClipboardEventReceiver {
        self.event_sender.subscribe()
    }

    /// Return the temporary directory path.
    pub fn temp_dir(&self) -> &str {
        &self.temp_dir
    }

    /// Return the shared event sender.
    pub fn event_sender(&self) -> &ClipboardEventSender {
        &self.event_sender
    }
}

impl CliprdrBackendFactory for RdpCliprdrFactory {
    fn build_cliprdr_backend(&self) -> Box<dyn CliprdrBackend> {
        Box::new(RdpCliprdrBackend::new(
            self.temp_dir.clone(),
            self.event_sender.clone(),
        ))
    }
}

/// Clipboard backend factory wired to the wrdp orchestrator runtime.
pub struct WrdpCliprdrFactory {
    clipboard_manager: Arc<Mutex<ClipboardOrchestrator>>,
    event_sender: ClipboardEventSender,
    server_event_sender: Option<mpsc::UnboundedSender<ironrdp_server::ServerEvent>>,
}

impl WrdpCliprdrFactory {
    /// Create a new orchestrator-wired clipboard backend factory.
    pub fn new(clipboard_manager: Arc<Mutex<ClipboardOrchestrator>>) -> Self {
        let event_sender = ClipboardEventSender::new();
        let event_receiver = event_sender.subscribe();

        info!("created clipboard backend factory with event channel");
        Self::start_event_bridge(event_receiver, Arc::clone(&clipboard_manager));

        Self {
            clipboard_manager,
            event_sender,
            server_event_sender: None,
        }
    }

    fn start_event_bridge(
        receiver: ClipboardEventReceiver,
        clipboard_manager: Arc<Mutex<ClipboardOrchestrator>>,
    ) {
        tokio::spawn(async move {
            info!("clipboard event bridge task started");

            loop {
                if let Some(rdp_event) = receiver.try_recv() {
                    let manager = clipboard_manager.lock().await;
                    let manager_tx = manager.event_sender();
                    drop(manager);

                    match rdp_event {
                        ClipboardEvent::RemoteCopy { formats } => {
                            info!("remote clipboard format list: {} formats", formats.len());

                            let _ = manager_tx
                                .send(
                                    crate::rdp::channels::clipboard::ClipboardEvent::RdpFormatList(
                                        clipboard_formats_from_rdp(&formats),
                                    ),
                                )
                                .await;
                        }
                        ClipboardEvent::FormatDataRequest { format_id } => {
                            let _ = manager_tx
                                .send(
                                    crate::rdp::channels::clipboard::ClipboardEvent::RdpDataRequest(
                                        format_id.value(),
                                        None,
                                    ),
                                )
                                .await;
                        }
                        ClipboardEvent::FormatDataResponse { data, is_error } => {
                            if is_error {
                                debug!(
                                    "remote clipboard data response reported unavailable format"
                                );
                                let _ = manager_tx
                                    .send(crate::rdp::channels::clipboard::ClipboardEvent::RdpDataError)
                                    .await;
                            } else {
                                let _ = manager_tx
                                    .send(crate::rdp::channels::clipboard::ClipboardEvent::RdpDataResponse(data))
                                    .await;
                            }
                        }
                        ClipboardEvent::FileContentsRequest {
                            stream_id,
                            index,
                            position,
                            size,
                            is_size_request,
                        } => {
                            let _ = manager_tx
                                .send(crate::rdp::channels::clipboard::ClipboardEvent::RdpFileContentsRequest {
                                    stream_id,
                                    list_index: index.try_into().unwrap_or(u32::MAX),
                                    position,
                                    size,
                                    is_size_request,
                                })
                                .await;
                        }
                        ClipboardEvent::FileContentsResponse {
                            stream_id,
                            data,
                            is_error,
                        } => {
                            let _ = manager_tx
                                .send(crate::rdp::channels::clipboard::ClipboardEvent::RdpFileContentsResponse {
                                    stream_id,
                                    data,
                                    is_error,
                                })
                                .await;
                        }
                        ClipboardEvent::Ready | ClipboardEvent::RequestFormatList => {
                            let _ = manager_tx
                                .send(crate::rdp::channels::clipboard::ClipboardEvent::RdpReady)
                                .await;
                        }
                        ClipboardEvent::NegotiatedCapabilities(_)
                        | ClipboardEvent::Lock { .. }
                        | ClipboardEvent::Unlock { .. } => {}
                    }
                } else {
                    tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
                }
            }
        });
    }

    /// Return a clone of the shared event sender.
    pub fn event_sender(&self) -> ClipboardEventSender {
        self.event_sender.clone()
    }
}

impl CliprdrBackendFactory for WrdpCliprdrFactory {
    fn build_cliprdr_backend(&self) -> Box<dyn CliprdrBackend> {
        debug!("building clipboard backend for new connection");
        Box::new(RdpCliprdrBackend::new(
            "/tmp/wrdp-clipboard".to_string(),
            self.event_sender.clone(),
        ))
    }
}

impl ServerEventSender for WrdpCliprdrFactory {
    fn set_sender(&mut self, sender: mpsc::UnboundedSender<ironrdp_server::ServerEvent>) {
        info!("clipboard factory received server event sender");
        self.server_event_sender = Some(sender.clone());

        let manager = Arc::clone(&self.clipboard_manager);
        tokio::spawn(async move {
            let manager = manager.lock().await;
            manager.set_server_event_sender(sender).await;
        });
    }
}

impl ironrdp_server::CliprdrServerFactory for WrdpCliprdrFactory {}

impl std::fmt::Debug for WrdpCliprdrFactory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WrdpCliprdrFactory")
            .field("has_server_sender", &self.server_event_sender.is_some())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rdp::channels::clipboard::manager::ClipboardOrchestratorConfig;

    #[test]
    fn event_channel_queues_events() {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();

        sender.send(ClipboardEvent::Ready);
        sender.send(ClipboardEvent::RequestFormatList);

        assert!(receiver.has_pending());
        let events = receiver.drain();
        assert_eq!(events.len(), 2);
        assert!(matches!(events[0], ClipboardEvent::Ready));
        assert!(matches!(events[1], ClipboardEvent::RequestFormatList));
        assert!(!receiver.has_pending());
    }

    #[test]
    fn backend_exposes_expected_capabilities() {
        let (backend, _) = RdpCliprdrBackend::create_with_channel("/tmp/test".to_string());
        let caps = backend.client_capabilities();

        assert!(caps.contains(ClipboardGeneralCapabilityFlags::USE_LONG_FORMAT_NAMES));
        assert!(caps.contains(ClipboardGeneralCapabilityFlags::STREAM_FILECLIP_ENABLED));
        assert!(caps.contains(ClipboardGeneralCapabilityFlags::CAN_LOCK_CLIPDATA));
        assert!(caps.contains(ClipboardGeneralCapabilityFlags::FILECLIP_NO_FILE_PATHS));
    }

    #[tokio::test]
    async fn server_factory_builds_backend() {
        let config = ClipboardOrchestratorConfig::default();
        let manager = Arc::new(Mutex::new(
            ClipboardOrchestrator::new(config).await.unwrap(),
        ));

        let factory = WrdpCliprdrFactory::new(manager);
        let _backend = factory.build_cliprdr_backend();
    }
}
